Qubes ebuilds bump, again
aidecoe/aidecoe-overlay pull request #4
Opened 2019-09-03 21:28 UTC by pzskc383

2019-09-11 22:05 UTC, aidecoe requested changes

2019-09-11 22:05 UTC, aidecoe commented on qubes-vm/qmemman/qmemman-4.0.22.ebuild
> +	newinitd "${FILESDIR}"/qubes-meminfo-writer.initd qubes-meminfo-writer
let's copy function from core-agent and use that for consistency. Later we will go through common functionality and put that together in an eclass or sth.

2019-09-11 22:05 UTC, aidecoe commented on qubes-vm/qmemman/qmemman-4.0.25.ebuild
> +	newinitd "${FILESDIR}"/qubes-meminfo-writer.initd qubes-meminfo-writer
let's copy function from core-agent and use that for consistency. Later we will go through common functionality and put that together in an eclass or sth.

2019-09-11 22:05 UTC, aidecoe commented on qubes-vm/qrexec/qrexec-4.0.39.ebuild
> +	newinitd vm-init.d/qubes-qrexec-agent
let's copy function from core-agent and use that for consistency. Later we will go through common functionality and put that together in an eclass or sth.

2019-09-11 22:05 UTC, aidecoe commented on qubes-vm/qrexec/qrexec-4.0.39.ebuild
> +	newinitd vm-init.d/qubes-qrexec-agent
isn't this missing second arg? or should it actually be `doinitd`?

2019-09-11 22:05 UTC, aidecoe commented on qubes-vm/qrexec/qrexec-4.0.47.ebuild
> +	doinitd ../vm-init.d/qubes-qrexec-agent
let's copy function from core-agent and use that for consistency. Later we will go through common functionality and put that together in an eclass or sth.

2019-09-12 00:15 UTC, marmarek commented on qubes-vm/db/files/no-systemd-deps.patch
> ++        // sd_notify(1, "READY=1");
There is more flexible approach at https://github.com/QubesOS/qubes-core-qubesdb/pull/8, but unfortunately it was never finished by the author.

2019-10-13 22:00 UTC, aidecoe commented on qubes-vm/gui-agent/gui-agent-4.0.24.ebuild
> +	)
gui-common package has something different. This is actually needed. Confusing.

2019-10-20 22:04 UTC, aidecoe commented
I have picked the changes manually and either fixed or skipped where I was not sure.

2019-10-20 22:04 UTC, closed without merging